### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by johngruen** [mozilla/concepts#73]
TODOS:
Matt, Gregg, and Rob:
- [ ] Verify copy for all experiments. Please be sure to text button text etc.
- [ ] Verify links for all experiments
- [ ] Verify that inbound links include appropriate parameters...these should be rc={recruitment channel} and rv={recruitment variant}
- [ ] Verify that survey link is correct and that all parameters are being passed

```
  const rc = encodeURIComponent(params.get('rc'))
  const rv = encodeURIComponent(params.get('rv'))
  const aid = metaCleanName
  const av = metaVariant
  const t = typeof window === 'object' ? navigator.doNotTrack === "1" : false
  const debug = encodeURIComponent(params.get('debug'))
  const surveyUrl = `${metaSurveyUrl}/?rc=${rc}&rv=${rv}&aid=${aid}&av=${av}&t=${t}&debug=${debug}`
```
- [ ] Verify that link to blog post is working across all variants
- [x] Provide VPN copy (we'll need to get images for this one????)

John and Wil
- [ ] Verify metrics are recording as intended
- [x] Add VPN page
- [ ] Deploy all to Prod
